"""make some columns nullable and alter VARCHAR length for some

Revision ID: ad2e3a5a9359
Revises: ed3380cf4a7c
Create Date: 2024-09-08 23:52:05.135573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ad2e3a5a9359"
down_revision: Union[str, None] = "ed3380cf4a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "superheroes",
        "full_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "superheroes", "intelligence", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "superheroes", "strength", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "superheroes", "speed", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "superheroes", "durability", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "superheroes", "power", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "superheroes", "combat", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "superheroes",
        "occupation",
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "superheroes",
        "base",
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "superheroes",
        "relatives",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "superheroes",
        "relatives",
        existing_type=sa.String(length=2000),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "superheroes",
        "base",
        existing_type=sa.String(length=2000),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "superheroes",
        "occupation",
        existing_type=sa.String(length=2000),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "superheroes", "combat", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "superheroes", "power", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "superheroes", "durability", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "superheroes", "speed", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "superheroes", "strength", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "superheroes", "intelligence", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "superheroes",
        "full_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
