"""add superheros and aliases tables

Revision ID: ed3380cf4a7c
Revises: 5697132a488a
Create Date: 2024-09-08 23:45:49.693750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3380cf4a7c'
down_revision: Union[str, None] = '5697132a488a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superheros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('alter_egos', sa.String(length=255), nullable=True),
    sa.Column('place_of_birth', sa.String(length=255), nullable=True),
    sa.Column('first_appearance', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('alignment', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('height_feet', sa.String(length=20), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('weight_lb', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('eye_color', sa.String(length=100), nullable=True),
    sa.Column('hair_color', sa.String(length=100), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('combat', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('base', sa.String(length=100), nullable=True),
    sa.Column('group_affiliation', sa.String(length=255), nullable=True),
    sa.Column('relatives', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aliases',
    sa.Column('alias_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('superhero_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['superhero_id'], ['superheros.id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliases')
    op.drop_table('superheros')
    # ### end Alembic commands ###
