apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: backend
      name: latest
      referencePolicy:
        type: ""
