apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: frontend
      name: latest
      referencePolicy:
        type: ""
