apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: mysql:8.0
      name: "8.0"
      referencePolicy:
        type: ""
